<?php
/**
 * CollectionIndexGenerator - Generates index pages for blog collections
 *
 * Responsibilities:
 * - Generate index.php for each collection (e.g., /blog/index.php, /news/index.php)
 * - Extract metadata from posts (title, date, excerpt)
 * - Apply templates to generate listing pages
 */

class CollectionIndexGenerator
{
    private string $rootDir;
    private string $templatesFile;
    private array $templates;

    public function __construct(string $rootDir, string $templatesFile)
    {
        $this->rootDir = rtrim($rootDir, '/');
        $this->templatesFile = $templatesFile;
        $this->loadTemplates();
    }

    /**
     * Load templates from config file
     */
    private function loadTemplates(): void
    {
        if (file_exists($this->templatesFile)) {
            $data = json_decode(file_get_contents($this->templatesFile), true);
            $this->templates = $data ?? [];
        } else {
            $this->templates = [];
        }
    }

    /**
     * Generate index page for a collection
     */
    public function generateIndex(array $collection, array $posts): void
    {
        $indexType = $collection['index_type'] ?? 'auto';

        if ($indexType === 'auto') {
            $this->generateStaticIndex($collection, $posts);
        } else {
            $this->generateDynamicIndex($collection);
        }
    }

    /**
     * Generate static index page
     */
    private function generateStaticIndex(array $collection, array $posts): void
    {
        $listTemplate = $this->templates['list_template'] ?? $this->getDefaultListTemplate();
        $postItemTemplate = $this->templates['post_item_template'] ?? $this->getDefaultPostItemTemplate();

        // Filter only published posts
        $publishedPosts = array_filter($posts, fn($post) => $post['status'] === 'published');

        // Sort posts by date (newest first)
        usort($publishedPosts, function($a, $b) {
            $dateA = $this->extractPostMeta($a['path'])['date'] ?? '';
            $dateB = $this->extractPostMeta($b['path'])['date'] ?? '';
            return strcmp($dateB, $dateA);
        });

        // Generate posts list HTML
        $postsListHtml = '';
        foreach ($publishedPosts as $post) {
            $meta = $this->extractPostMeta($post['path']);

            $postHtml = $postItemTemplate;
            $postHtml = str_replace('{TITLE}', htmlspecialchars($meta['title']), $postHtml);
            $postHtml = str_replace('{DATE}', htmlspecialchars($meta['date']), $postHtml);
            $postHtml = str_replace('{EXCERPT}', htmlspecialchars($meta['excerpt']), $postHtml);
            $postHtml = str_replace('{SLUG}', htmlspecialchars($post['slug']), $postHtml);
            $postHtml = str_replace('{COLLECTION_BASE_PATH}', htmlspecialchars($collection['base_path']), $postHtml);

            $postsListHtml .= $postHtml . "\n";
        }

        // If no posts, show empty message
        if (empty($postsListHtml)) {
            $postsListHtml = '<p>No posts yet.</p>';
        }

        // Generate final index HTML
        $indexHtml = $listTemplate;
        $indexHtml = str_replace('{COLLECTION_LABEL}', htmlspecialchars($collection['label']), $indexHtml);
        $indexHtml = str_replace('{POSTS_LIST}', $postsListHtml, $indexHtml);

        // Write to file
        $indexPath = $this->rootDir . '/' . $collection['base_path'] . '/index.php';
        $indexDir = dirname($indexPath);

        if (!is_dir($indexDir)) {
            mkdir($indexDir, 0755, true);
        }

        file_put_contents($indexPath, $indexHtml);
    }

    /**
     * Generate dynamic index page (PHP that scans directory)
     */
    private function generateDynamicIndex(array $collection): void
    {
        $indexPath = $this->rootDir . '/' . $collection['base_path'] . '/index.php';
        $indexDir = dirname($indexPath);

        if (!is_dir($indexDir)) {
            mkdir($indexDir, 0755, true);
        }

        // Create PHP code that dynamically lists posts
        $dynamicCode = <<<'PHP'
<?php
/**
 * Dynamic blog index - automatically lists all posts in this collection
 * Generated by CollectionIndexGenerator
 */

// Scan current directory for post directories
$posts = [];
$currentDir = __DIR__;
$items = scandir($currentDir);

foreach ($items as $item) {
    if ($item === '.' || $item === '..' || $item === 'index.php') {
        continue;
    }

    $itemPath = $currentDir . '/' . $item;
    if (is_dir($itemPath) && file_exists($itemPath . '/index.php')) {
        // Extract post metadata
        $postContent = file_get_contents($itemPath . '/index.php');

        // Extract title
        preg_match('/<title>(.*?)<\/title>/i', $postContent, $titleMatch);
        $title = $titleMatch[1] ?? ucwords(str_replace('-', ' ', $item));

        // Extract date from meta tag
        preg_match('/<meta[^>]+name=["\']date["\'][^>]+content=["\']([^"\']+)/i', $postContent, $dateMatch);
        $date = $dateMatch[1] ?? '';

        // Extract excerpt from meta description
        preg_match('/<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']+)/i', $postContent, $excerptMatch);
        $excerpt = $excerptMatch[1] ?? '';

        $posts[] = [
            'slug' => $item,
            'title' => $title,
            'date' => $date,
            'excerpt' => $excerpt,
        ];
    }
}

// Sort by date (newest first)
usort($posts, function($a, $b) {
    return strcmp($b['date'], $a['date']);
});
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <header>
        <nav>
            <a href="/">Home</a>
        </nav>
    </header>

    <main>
        <h1>Blog</h1>
        <div class="posts-list">
            <?php if (empty($posts)): ?>
                <p>No posts yet.</p>
            <?php else: ?>
                <?php foreach ($posts as $post): ?>
                    <article class="post-item">
                        <h2><a href="<?php echo htmlspecialchars($post['slug']); ?>/"><?php echo htmlspecialchars($post['title']); ?></a></h2>
                        <p class="date"><?php echo htmlspecialchars($post['date']); ?></p>
                        <p class="excerpt"><?php echo htmlspecialchars($post['excerpt']); ?></p>
                        <a href="<?php echo htmlspecialchars($post['slug']); ?>/">Read more</a>
                    </article>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </main>

    <footer>
        <p>&copy; <?php echo date('Y'); ?> All rights reserved.</p>
    </footer>
</body>
</html>
PHP;

        file_put_contents($indexPath, $dynamicCode);
    }

    /**
     * Extract metadata from a post
     */
    public function extractPostMeta(string $postPath): array
    {
        if (!file_exists($postPath)) {
            return [
                'title' => '',
                'date' => '',
                'excerpt' => '',
            ];
        }

        $content = file_get_contents($postPath);

        // Extract title from <title> tag
        preg_match('/<title>(.*?)<\/title>/i', $content, $titleMatch);
        $title = $titleMatch[1] ?? '';

        // Remove " - Blog" or similar suffix
        $title = preg_replace('/\s*-\s*.*$/', '', $title);

        // Extract date from meta tag
        preg_match('/<meta[^>]+name=["\']date["\'][^>]+content=["\']([^"\']+)/i', $content, $dateMatch);
        $date = $dateMatch[1] ?? '';

        // Extract excerpt from meta description
        preg_match('/<meta[^>]+name=["\']description["\'][^>]+content=["\']([^"\']+)/i', $content, $excerptMatch);
        $excerpt = $excerptMatch[1] ?? '';

        return [
            'title' => $title,
            'date' => $date,
            'excerpt' => $excerpt,
        ];
    }

    /**
     * Default list template
     */
    private function getDefaultListTemplate(): string
    {
        return <<<'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
<?php /* CMS:BLOCK name=head role=meta start */ ?>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{COLLECTION_LABEL}</title>
    <meta name="description" content="Browse all {COLLECTION_LABEL} posts">
<?php /* CMS:BLOCK name=head end */ ?>
</head>
<body>
<?php /* CMS:BLOCK name=header role=navigation start */ ?>
    <header>
        <nav>
            <a href="/">Home</a>
            <a href="/blog/">Blog</a>
        </nav>
    </header>
<?php /* CMS:BLOCK name=header end */ ?>

<?php /* CMS:BLOCK name=content start */ ?>
    <main>
        <h1>{COLLECTION_LABEL}</h1>
        <div class="posts-list">
            {POSTS_LIST}
        </div>
    </main>
<?php /* CMS:BLOCK name=content end */ ?>

<?php /* CMS:BLOCK name=footer start */ ?>
    <footer>
        <p>&copy; <?php echo date('Y'); ?> All rights reserved.</p>
    </footer>
<?php /* CMS:BLOCK name=footer end */ ?>
</body>
</html>
HTML;
    }

    /**
     * Default post item template
     */
    private function getDefaultPostItemTemplate(): string
    {
        return <<<'HTML'
<article class="post-item">
    <h2><a href="/{COLLECTION_BASE_PATH}/{SLUG}/">{TITLE}</a></h2>
    <p class="date">{DATE}</p>
    <p class="excerpt">{EXCERPT}</p>
    <a href="/{COLLECTION_BASE_PATH}/{SLUG}/">Read more</a>
</article>
HTML;
    }
}
